### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by panda82** [char101/xposed-qslock#1]
Still doesn't work on Android Pie.

**Comment by char101** [comment]
It works on my OP6 running Pie.

**Comment by panda82** [comment]
It worked before for me but after a while it's not working. I have samsung note 3...

**Comment by panda82** [comment]
Now I can't pause or play music from the lock screen player...

**Comment by char101** [comment]
This module only calls `StatusBarManager.disable2` to disable the quick settings and the notification shade. As for the effect(s) it has on the ROM itself is up to the ROM implementation. I have tried it on OxygenOS Pie and Nougat Touchwiz and it worked.
